DJ_Financer/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from django.contrib.auth import views as auth_view
from accounts import views as account_views
from transaction import views as trans_views
from accounts.forms import SignInFrom, RegisterForm


urlpatterns = [
    path('', account_views.home_view, name='home'),
    path('admin/', admin.site.urls),
    path('home/', account_views.home_view, name='home'),
    path('transactions/', include(('transaction.urls', 'transactions'),namespace='transactions')),
    # path('account/', include('accounts.urls')),
    path('login/', auth_view.LoginView.as_view(authentication_form=SignInFrom, template_name='accounts/login.html'), name='login'),
    path('logout/', auth_view.LogoutView.as_view(template_name='accounts/logout.html'), kwargs= {'placeholder':'Yeet'}, name='logout'),
    path('register/', account_views.register_view, name='register'),
    path('account/', account_views.initial_view, name='initial'),
]

transaction/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('edit/', views.edit_view),
    path('upload/', views.upload_view, name='upload'),
    path('oversight/', views.oversight_view, name='oversight'),
]

transaction/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from django.db import migrations

class Transaction(models.Model):
    kind            = models.CharField(max_length=150)
    date            = models.DateField(default=timezone.now)
    amount          = models.DecimalField(max_digits=100, decimal_places=2)
    name            = models.CharField(max_length=150)
    description     = models.CharField(max_length=1000, blank=True)
    category        = models.CharField(max_length=150, blank=True)
    counterparty    = models.CharField(max_length=150, blank=True)
    account         = models.CharField(max_length=150, blank=True)
    owner           = models.ForeignKey(User, on_delete=models.CASCADE)

    class Meta: 
        ordering = ['-owner', '-date']

class CsvFile(models.Model):
    csv = models.FileField(upload_to='transaction/cache')
    owner = models.ForeignKey(User, on_delete=models.CASCADE)

transaction/forms.py
from django import forms
from django.contrib.auth.models import User
from django.utils import timezone
from category.models import Category, CATEGORY_CHOICES

TRANSACTION_TYPES =(
    ('1','Incasso'),
    ('2','Batch payment'),
    ('3','Batch payment'),
    ('4','Branch withdrawal'),
    ('5','Cash machine'),
    ('6','Deposit'),
    ('7','Online Banking'),
    ('8','Payment terminal'),
    ('9','SEPA direct debit'),
    ('10','Sundries'),
    ('11','Transfer'),
)

class TransactionForm(forms.Form):
    def __init__(self, user, *args, **kwargs):
        self.owner = user
        super(CsvFileForm, self).__init__(*args, **kwargs)

    classification  = forms.ChoiceField(label='classification*', choices=TRANSACTION_TYPES)
    amount          = forms.DecimalField(label='amount*', max_digits=100, decimal_places=2)
    date            = forms.DateField(label='date*', initial=timezone.now)
    name            = forms.CharField(label='name*', max_length=150)
    description     = forms.CharField(label='description', max_length=1000)
    counterparty    = forms.CharField(label='counterparty', max_length=150)
    account         = forms.CharField(label='account', max_length=150)
    category        = forms.ChoiceField(label='category', choices=CATEGORY_CHOICES)

transaction/views.py
from .models import Transaction
from django import forms
from django.template.loader import render_to_string
from django.shortcuts import render, redirect
from .forms import TransactionForm
from datetime import datetime
from django.contrib.auth.decorators import login_required
from static.scripts.csv_interpreter import handle_file

def home_widget(request):
    total_count = Transaction.objects.filter(owner=request.user).count()
    if total_count > 5:
        show_count = 5
    else: show_count = total_count
    show_content = reversed( Transaction.objects.order_by('-id')[:show_count] )
    text = f'These are your last {show_count} transactions. And here will go some more information about some other crap'
    content = {
        'total_count'   : total_count,
        'show_count'    : show_count,
        'show_content'  : show_content,
        'text'          : text
    }
    return render(request, 'transaction/transaction_widget.html', content)

def edit_view(request):
    context = {
        'form': TransactionForm,
        'now' : datetime.now,
        'user' : request.user
    }
    return render(request, 'transaction/edit.html', context)

@login_required
def upload_view(request):
    if request.method == 'POST':
        if len(request.FILES) != 0:
            error = handle_file(user=request.user, csv=request.FILES['csv'])
            print(f'\n {error} \n')
            if error:
                return render(request, 'transaction/upload.html', {'error': error})
            return redirect('home')
        return render(request, 'transaction/upload.html', {'error': 'Please select a file'})
    return render(request, 'transaction/upload.html')

@login_required
def oversight_view(request):
    user_transactions = Transaction.objects.filter(owner=request.user)
    context = {
        'transactions' : user_transactions,
    }
    return render(request, 'transaction/oversight.html', context)

templates/transaction/edit.html
{% extends "base.html" %}

{% block title %}Test Page{% endblock %}

{% block content %}
<div class="w-layout-grid about-grid mainbox">
    <div id="w-node-boxright">
        <div class="home-section-wrap">
            <h1 class="form-head">Transaction</h1>
            <form class="app-form" method="POST">
                {% csrf_token %}
                {{ form.as_p }}
            </form>
        </div>
        <div class="form-group">
            <button class="button  fit-content" type="submit">Save</button>
        </div>
    </div>
</div>
{% endblock %}

templates/transaction/oversight.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>{%block title%}VF Page{%endblock title%}</title>
        <link rel="shortcut icon" href="">
        <link rel="stylesheet" type="text/css" href="{% static "css/styles.css" %}" >
        <script src="{% static 'js/main.js' %}"></script> 
    </head>
    <div class="nav-bar">
      <div class="inner-nav">
        <a href="{% url 'home' %}"><h1 class="logo-small ">spae.</h1></a>
        <nav>
          <a href="{% url 'logout' %}" class="sub-text w mg-70">logout</a>
        </nav>
      </div>
    </div>
<body class="bg-prim">
<div class="home-content-wrap">
    <div class="main-container">
        <table class="body-text w trans-table">
            <tr class="sub-text w">
                <th class="u-line">All Transactions</th>
                <th>{{ date }}</th>
            </tr>

            <tr class="sub-text b"><th><br></th></tr>
            {% for trans in transactions %}

            <tr onclick="toggleSpinTable('{{ forloop.counter|escapejs }}'),toggleDisplay('{{ forloop.counter|escapejs }}')">
                <td>{{ trans.name }}</th>
                <td>$ {{ trans.amount }}</th>
                <td>
                <button 
                    type="button" 
                    onclick="toggleSpinTable('{{ forloop.counter|escapejs }}'), toggleDisplay('{{ forloop.counter|escapejs }}')" 
                    id = "spin_id_{{ forloop.counter }}"
                    class="spin-btn-table w">+
                </button>
                </td>
            </tr>

            <tr id="drop_id_{{ forloop.counter }}" class="hide small">
                <td>{{ trans.description }}</td>
                <td colspan="2">
                    <a class="menu-ref w">edit</a><br>
                    <a class="menu-ref w">delete</a>
                </td>
            </tr>
            {% endfor %}
        </table>
    </div>
  </div>
</body>
</html>

templates/transaction/upload.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>{%block title%}VF Page{%endblock title%}</title>
        <link rel="shortcut icon" href="">
        <link rel="stylesheet" type="text/css" href="{% static "css/styles.css" %}" >
        <script src="{% static 'js/main.js' %}"></script> 
    </head>
    <body class="bg-prim">
        <form method="POST" action="{% url 'transactions:upload' %}" enctype="multipart/form-data">
            <div class="circle-wrap-middle">
                <div class="circle" id=dropzone>
                    <div class='circle-inner'>
                        <label class="prim circle-text">Drop your csv here</label>
                        {% csrf_token %}
                        <div class="center-box">
                            <input type="file" name="csv" class="prim input">
                        </div>
                        <div class="center-box">
                            {% if error %}
                                <div class="error-box">
                                    <a class="small prim">( ERROR: {{ error }} )</a>
                                </div> 
                            {% endif %}
                        </div>
                    </div>
                </div> 
            </div>
            <button class="button pos-fixed" id="btn-login"type="submit"></button>
        </form>
        <a id="btn-cancel" type="submit" href="{% url 'home' %}"></a>
    </body>
</html>